apiVersion: v1
kind: Pod
metadata:
  name: <pod-name>
spec:
  schedulerName: spyre-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: spyre-container
      imagePullPolicy: Always
      # image: registry.redhat.io/rhaiis/vllm-spyre-rhel9:3.3.0-1771459423
      image: registry.redhat.io/rhaii-early-access/vllm-spyre-rhel9:3.4.0-ea.2
      resources:
        limits:
          ibm.com/spyre_pf: 1
        requests:
          ibm.com/spyre_pf: 1
      workingDir: /tmp/
      command:
        - bash
        - '-c'
      args:
        - |
          # 1. Strip it from the current running script
          unset HF_HUB_OFFLINE
          
          # 2. Permanently strip it for future 'kubectl exec' sessions
          echo "unset HF_HUB_OFFLINE" >> ~/.bashrc
          echo "unset HF_HUB_OFFLINE" >> /etc/profile
          echo "unset HF_HUB_OFFLINE" >> ~/.bash_profile 
          echo "unset HF_HUB_OFFLINE" >> ~/.zshrc
          
          pip3 install --no-deps --index-url https://pypi.org/simple aiu-fms-testing-utils==0.7.1
          pip3 install sentence-transformers --index-url https://pypi.org/simple --no-deps
          git clone https://github.com/IBM/deepview.git 
          cd deepview
          pip3 install -e . --index-url https://pypi.org/simple --no-deps
          sleep infinity
      env:
        - name: HOME
          value: /opt/app-root/src
        - name: AIU_TOPO_FILE
          value: /etc/ibm/spyre/topo.json
        - name: HF_HUB_CACHE
          value: /shared/.cache
        - name: FLEX_COMPUTE
          value: SENTIENT
        - name: FLEX_DEVICE
          value: PF
        - name: TORCH_SENDNN_CACHE_DIR
          value: /dev/shm/cache
      volumeMounts:
        - mountPath: /dev/shm
          name: dev-shm
        - mountPath: "/shared"
          name: shared
  volumes:
    - name: dev-shm
      emptyDir:
        medium: Memory
        sizeLimit: 32Gi
    - name: shared
      emptyDir: {}
