# Standard
from pathlib import Path

# Third Party
import pytest


@pytest.fixture
def model_output_file():
    """
    Fixture that returns 'model_output.txt' generated by model runner.
    """

    model_output_file = Path.cwd() / "model_output.txt"
    return model_output_file
