# /*******************************************************************************
#  * Copyright 2025 IBM Corporation
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *     http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
# *******************************************************************************/

# Standard
from pathlib import Path
import argparse

# Third Party
import pytest

# Local
from deepview.core.model_runner import run_model


@pytest.fixture(scope="module", autouse=True)
def debugger_path(tmp_path_factory):
    """
    A fixture to run the model and generate the debugger output file.
    This fixture is automatically used in tests that require the debugger output.
    It runs the model with the specified arguments and saves the output to a temporary file.
    It same as call `deepview --model_type <model_type> --model <model_path> --mode <deepview_mode> --show_details --generate_repro_code --output_file <tool_output_file>`

    Args:
        tmp_path_factory: A pytest fixture that provides a temporary directory for testing.

    Returns:
        debugger_path (Path): The path to the debugger output file generated by the model.
    """
    args = argparse.Namespace(
        model_type="fms",
        model_path=str(
            Path.home() / "models" / "ibm-granite" / "granite-3.3-2b-instruct"
        ),
        tool_output_file=tmp_path_factory.getbasetemp() / "test_debugger.txt",
        deepview_mode=["layer_debugging"],
        show_details_flag=True,
        generate_repro_code_flag=True,
        logfile=tmp_path_factory.getbasetemp() / "test_model_output.txt",
    )

    run_model(
        args.model_type,
        args.model_path,
        args.tool_output_file,
        args.deepview_mode,
        args.show_details_flag,
        args.generate_repro_code_flag,
        args.logfile,
    )
    debugger_path = tmp_path_factory.getbasetemp() / "test_debugger.txt"
    return debugger_path


@pytest.fixture
def model_output_file(tmp_path_factory):
    """
    Fixture that returns 'test_model_output.txt' generated by model runner.
    """

    return tmp_path_factory.getbasetemp() / "test_model_output.txt"


def test_debugger_output_exits(debugger_path):
    """
    Test to ensure the debugger output file exists after running the model.
    debugger_path is a fixture that runs the model and generates the output file.

    Args:
        debugger_path: A fixture that runs the model and generates the output file.
    """
    assert (
        debugger_path.exists()
    ), f"Debugger output file {debugger_path} does not exist."


def test_layer_debugging_mode(model_output_file):
    """
    Test to ensure the layer debugging mode is correctly set in the debugger output.

    Args:
        model_output_file: A fixture that uses the test_model_output.txt file generated by the model runner.
    """
    assert "Running each layer individually" in model_output_file.read_text(
        encoding="utf-8"
    ), "Expected Running each layer individually"
    assert (
        "DEEPVIEW Successfully ran model.base_model.embedding, [1, 1], torch.int64\n"
        in model_output_file.read_text(encoding="utf-8")
    ), "Expected Successfully ran model.base_model.embedding"
    assert (
        "DEEPVIEW \033[1mError running model.base_model.layers[0].attn, [1, 1, 2048], torch.float16\n"
        in model_output_file.read_text(encoding="utf-8")
    ), "Expected Error running model.base_model.layers[0].attn"
