# /*******************************************************************************
#  * Copyright 2025 IBM Corporation
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *     http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
# *******************************************************************************/

# Standard
from pathlib import Path
import argparse

# Third Party
import pytest

# Local
from deepview.core.model_runner import run_model


@pytest.fixture(scope="module", autouse=True)
def debugger_path(tmp_path_factory, request):
    """
    A fixture to run the model and generate the debugger output file.
    This fixture is automatically used in tests that require the debugger output.
    It runs the model with the specified arguments and saves the output to a temporary file.
    It same as call `deepview --model_type <model_type> --model <model_path> --mode <deepview_mode> --show_details --generate_repro_code --output_file <tool_output_file>`

    Args:
        tmp_path_factory: A pytest fixture that provides a temporary directory for testing.
        request: Pytest request object to access command-line options.

    Returns:
        debugger_path (Path): The path to the debugger output file generated by the model.
    """
    # Build deepview_mode list based on command-line arguments
    deepview_mode = ["unsupported_op"]
    if request.config.getoption("--layer_debugging"):
        deepview_mode.append("layer_debugging")

    args = argparse.Namespace(
        model_type="fms",
        model_path=str(
            Path.home() / "models" / "mistralai" / "Mistral-7B-Instruct-v0.3"
        ),
        tool_output_file=tmp_path_factory.getbasetemp() / "test_debugger.txt",
        deepview_mode=deepview_mode,
        show_details_flag=True,
        generate_repro_code_flag=True,
        logfile=tmp_path_factory.getbasetemp() / "test_model_output.txt",
    )

    run_model(
        args.model_type,
        args.model_path,
        args.tool_output_file,
        args.deepview_mode,
        args.show_details_flag,
        args.generate_repro_code_flag,
        args.logfile,
    )
    debugger_path = tmp_path_factory.getbasetemp() / "test_debugger.txt"
    return debugger_path


@pytest.fixture
def model_output_file(tmp_path_factory):
    """
    Fixture that returns 'test_model_output.txt' generated by model runner.
    """

    return tmp_path_factory.getbasetemp() / "test_model_output.txt"


def test_debugger_output_exits(debugger_path):
    """
    Test to ensure the debugger output file exists after running the model.
    debugger_path is a fixture that runs the model and generates the output file.

    Args:
        debugger_path: A fixture that runs the model and generates the output file.
    """
    assert (
        debugger_path.exists()
    ), f"Debugger output file {debugger_path} does not exist."


def test_get_unsupported_ops(model_output_file):
    """
    Test to ensure the unsupported operations are correctly extracted from the debugger output.

    Args:
        debugger_path: A fixture that runs the model and generates the output file.
    """
    assert (
        "DEEPVIEW \033[1mNo unsupported operations detected.\033[0m\n"
        in model_output_file.read_text(encoding="utf-8")
    ), "Expected 'DEEPVIEW \033[1mNo unsupported operations detected.\033[0m\n'"


def test_layer_debugging_mode(model_output_file, request):
    """
    Test to ensure the layer debugging mode is correctly set in the debugger output.
    Only runs when --layer_debugging argument is passed to pytest.

    Args:
        model_output_file: A fixture that uses the test_model_output.txt file generated by the model runner.
        request: Pytest request object to access command-line options.
    """
    # Skip test if --layer_debugging argument not provided
    if not request.config.getoption("--layer_debugging"):
        pytest.skip("Test requires --layer_debugging argument")

    assert "Running each layer individually" in model_output_file.read_text(
        encoding="utf-8"
    ), "Expected Running each layer individually"
    assert (
        "DEEPVIEW Successfully ran model.base_model.layers[31].ff_sub_layer, [1, 64, 4096], torch.float16\n"
        in model_output_file.read_text(encoding="utf-8")
    ), "Expected Successfully ran model.base_model.layers[31].ff_sub_layer"
    assert (
        "DEEPVIEW Successfully ran model.base_model.dec_norm, [1, 64, 4096], torch.float16\n"
        in model_output_file.read_text(encoding="utf-8")
    ), "Expected Successfully ran model.base_model.dec_norm"
    assert (
        "DEEPVIEW Successfully ran model.base_model, [1, 64], torch.int64\n"
        in model_output_file.read_text(encoding="utf-8")
    ), "Expected Successfully ran model.base_model"
    assert (
        "DEEPVIEW Successfully ran model.head, [1, 4096], torch.float16\n"
        in model_output_file.read_text(encoding="utf-8")
    ), "Expected Successfully ran model.head"
    assert (
        "DEEPVIEW Successfully ran model, [1, 64], torch.int64\n"
        in model_output_file.read_text(encoding="utf-8")
    ), "Expected Successfully ran model"
