# /*******************************************************************************
#  * Copyright 2025 IBM Corporation
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *     http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
# *******************************************************************************/

# Standard
import argparse

# Third Party
import pytest

# Local
from deepview.core.model_runner import run_model


@pytest.fixture(scope="module", autouse=True)
def debugger_path(tmp_path_factory):
    """
    A fixture to run the model and generate the debugger output file.
    This fixture is automatically used in tests that require the debugger output.
    It runs the model with the specified arguments and saves the output to a temporary file.
    It same as call `deepview --model_type <model_type> --model <model_path> --mode <deepview_mode> --show_details --generate_repro_code --output_file <tool_output_file>`

    Args:
        tmp_path_factory: A pytest fixture that provides a temporary directory for testing.

    Returns:
        debugger_path (Path): The path to the debugger output file generated by the model.
    """
    args = argparse.Namespace(
        model_type="hf",
        model_path="ibm-ai-platform/Bamba-9B-v1",
        tool_output_file=tmp_path_factory.getbasetemp() / "test_debugger.txt",
        deepview_mode=["unsupported_op"],
        show_details_flag=True,
        generate_repro_code_flag=True,
        logfile=tmp_path_factory.getbasetemp() / "test_model_output.txt",
    )

    run_model(
        args.model_type,
        args.model_path,
        args.tool_output_file,
        args.deepview_mode,
        args.show_details_flag,
        args.generate_repro_code_flag,
        args.logfile,
    )
    debugger_path = tmp_path_factory.getbasetemp() / "test_debugger.txt"
    return debugger_path


@pytest.fixture
def model_output_file(tmp_path_factory):
    """
    Fixture that returns 'test_model_output.txt' generated by model runner.
    """

    return tmp_path_factory.getbasetemp() / "test_model_output.txt"


def test_debugger_output_exits(debugger_path):
    """
    Test to ensure the debugger output file exists after running the model.
    debugger_path is a fixture that runs the model and generates the output file.

    Args:
        debugger_path: A fixture that runs the model and generates the output file.
    """
    assert (
        debugger_path.exists()
    ), f"Debugger output file {debugger_path} does not exist."


def test_get_unsupported_ops(model_output_file):
    """
    Test to ensure the unsupported operations are correctly extracted from the debugger output.

    Args:
        debugger_path: A fixture that runs the model and generates the output file.
    """
    assert "DEEPVIEW Unsupported operations list:\n" in model_output_file.read_text(
        encoding="utf-8"
    ), "Expected 'DEEPVIEW Unsupported operations list:\n' in debugger output."

    unique_unsupported_ops = [
        "triu",
        "gt",
        "copy",
        "slice_scatter",
        "cos",
        "sin",
        "constant_pad_nd",
        "softplus",
        "roll",
        "select_scatter",
    ]
    unique_unsupported_ops_str = "\n".join(sorted(unique_unsupported_ops))
    assert (
        f"\033[1m{unique_unsupported_ops_str}\033[0m\n"
        in model_output_file.read_text(encoding="utf-8")
    ), "Expected match unsupported ops known in debugger output."
