# /*******************************************************************************
#  * Copyright 2025 IBM Corporation
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License");
#  * you may not use this file except in compliance with the License.
#  * You may obtain a copy of the License at
#  *
#  *     http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software
#  * distributed under the License is distributed on an "AS IS" BASIS,
#  * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  * See the License for the specific language governing permissions and
#  * limitations under the License.
# *******************************************************************************/

# Standard
import os

# Third Party
import pytest

# Local
from deepview.core.model_runner import set_environment


@pytest.fixture
def model_output_file(tmp_path_factory):
    """
    Fixture that returns 'test_model_output.txt' generated by model runner.
    """

    return tmp_path_factory.getbasetemp() / "test_model_output.txt"


def test_set_environment(model_output_file):
    """
    Test to ensure the environment variables are set correctly.
    This test checks that the old model output file is deleted if it exists,
    and that the environment variables are set to the expected values.

    Args:
        model_output_file: A fixture that provides a temporary file path for the model output.
    """
    set_environment()
    assert os.path.exists(model_output_file)
    assert os.environ["DTLOG_LEVEL"] == "error"
    assert os.environ["TORCH_SENDNN_LOG"] == "CRITICAL"
    assert os.environ["DT_DEEPRT_VERBOSE"] == "-1"
    assert os.environ["PYTHONUNBUFFERED"] == "1"
