# Allows running specific modules/layers in isolation with preserved context
import torch
import re
import sys
import os
import time
from fms.models import get_model
from fms.utils.generation import generate
from fms.utils import tokenizers
from torch_sendnn import torch_sendnn

from core.generate_minimal_repro import generate_repro_code


class PrintOutput:
    def __init__(self, file_path, stream):
        self.file = open(file_path, 'a')
        self.stream = stream
    def write(self, data):
        self.stream.write(data)
        self.file.write(data)
    def flush(self):
        self.stream.flush()
        self.file.flush()
    def isatty(self):
        return self.stream.isatty()
    def fileno(self):
        return self.stream.fileno()
    def close(self):
        self.file.close()


def set_environment():
    os.environ['DTLOG_LEVEL'] = 'error'
    os.environ['TORCH_SENDNN_LOG'] = 'CRITICAL'
    os.environ['DT_DEEPRT_VERBOSE'] = '-1'
    os.environ['PYTHONUNBUFFERED'] = '1'


def load_model_and_create_input(model_path):
    global model, device, prompt, input_id

    # Load the model
    print("Loading model")
    loading_model_time = time.time()
    model = get_model("hf_pretrained", None, model_path=model_path, device_type="cpu", data_type=torch.float16, source=None, distributed_strategy=None, fused_weights=False)
    tokenizer = tokenizers.get_tokenizer(model_path)
    # Comment out the line below to run the whole model. 
    model.base_model.layers  = model.base_model.layers[:1]
    model.eval()
    torch.set_grad_enabled(False)
    loading_model_time = time.time() - loading_model_time
    print(f"Loading complete, took {loading_model_time:.3f}s")

    # Compile the model
    print("Compiling model")
    compiling_model_time = time.time()
    device = torch.device("cpu")
    model.compile(backend="sendnn_decoder", dynamic=False)
    compiling_model_time = time.time() - compiling_model_time
    print(f"Compiling complete, took {compiling_model_time:.3f}s")

    # Create the prompt input
    prompt = "What is the capital of India?"
    tokens = tokenizer.tokenize(prompt)
    ids_l = tokenizer.convert_tokens_to_ids(tokens)
    ids_l = [tokenizer.bos_token_id] + ids_l
    ids_l = torch.tensor(ids_l, dtype=torch.long, device=device)
    input_id = ids_l


def infer():
    extra_generation_kwargs = None
    max_seq_len = max(len(prompt), model.config.max_expected_seq_len)
    result = generate(model,input_id,do_sample=False,max_new_tokens=2, max_seq_len=max_seq_len,extra_kwargs=extra_generation_kwargs)
    print(result)


def process_output(tool_output_file, logfile):
    # All DEBUG TOOL output lines are extracted and saved in tool_output_file.
    flag = False
    unknown_nodes = []
    with open(logfile, "r") as infile, open(tool_output_file, "w") as outfile:
        for line in infile:
            if line.startswith("DEBUG TOOL"):
                flag = True
                outfile.write(line)
                match = re.search(r'DEBUG TOOL Caught error for (.*?):', line)
                if match:
                    node = match.group(1)
                    unknown_nodes.append(node)

        unknown_nodes_str = '\n'.join(sorted(set(unknown_nodes)))
        final_line = (
            "DEBUG TOOL========================================================================\n"
            "DEBUG TOOL Unsupported operations list:\n"
            f"{unknown_nodes_str}"
        )
        print(final_line)
        outfile.write(final_line + "\n")
        if not flag:
            no_unsup_op = (
                "DEBUG TOOL========================================================================\n"
                "DEBUG TOOL \033[1mNo unsupported operations detected.\033[0m\n"
            )
            print(no_unsup_op)
            outfile.write(no_unsup_op)
    return flag


def run_model(model_path, tool_output_file, generate_repro_code_flag, logfile='model_output.txt'):
    if generate_repro_code_flag:
        torch_sendnn.preserve_lazyhandle()

    load_model_and_create_input(model_path)

    # Prints generated by compile_and_infer are shown in terminal as well as saved in logfile.
    original_stdout = sys.stdout
    original_stderr = sys.stderr
    tee_stdout = PrintOutput(logfile, original_stdout)
    tee_stderr = PrintOutput(logfile, original_stderr)
    sys.stdout = tee_stdout
    sys.stderr = tee_stderr
    try:
        infer()  
    except Exception as e:
        print(f"Exception occurred: {e}", file=original_stderr)
    finally:
        tee_stdout.flush()
        tee_stderr.flush()
        sys.stdout = original_stdout
        sys.stderr = original_stderr
        tee_stdout.close()
        tee_stderr.close()

    # Process the logfile to create the tool_output_file 
    flag = process_output(tool_output_file, logfile)

    # Generate reproduction code for unsupported ops (if any)
    if generate_repro_code_flag:
        if flag:
            print("Generating reproduction code")
            generate_repro_code()
        else:
            print("No reproduction code generated as no unsupported operations found.")

    # Update lazyhandle after first run of inference
    print("Updating lazyhandle")
    torch_sendnn.update_lazyhandle()