apiVersion: v1
kind: Pod
metadata:
  name: <pod-name>
spec:
  schedulerName: aiu-scheduler
  containers:
  - name: <pod-name>
    resources:
      limits:
        ibm.com/aiu_pf: 1
      requests:
        ibm.com/aiu_pf: 1
    imagePullPolicy: Always
    image: &pod_image icr.io/ibmaiu_internal/1.0/x86_64/spyre:dev
    command:
      - bash
      - '-c'
    args:
      # lines without gap are considered on the same line and indented are new lines
      - >
        source ~/.bashrc
        
        cd $HOME

        pip3 install -q -U transformers
        
        echo "POD_IMAGE:" $POD_IMAGE >> /tmp/aiu-query-devices.txt

        echo " " >> /tmp/aiu-query-devices.txt

        /opt/sentient/bin/aiu-query-devices >> /tmp/aiu-query-devices.txt

        echo " " >> ~/.bashrc

        echo "cat /tmp/aiu-query-devices.txt" >> ~/.bashrc

        echo 'FLEX_COMPUTE      = ' $FLEX_COMPUTE

        echo 'FLEX_DEVICE       = ' $FLEX_DEVICE

        echo 'DTLOG_LEVEL       = ' $DTLOG_LEVEL

        echo 'TORCH_SENDNN_LOG  = ' $TORCH_SENDNN_LOG

        echo 'DT_DEEPRT_VERBOSE = ' $DT_DEEPRT_VERBOSE

        echo 'INFER_SCRIPT      = ' $INFER_SCRIPT

        echo 'MODEL             = ' $MODEL

        tail -f /dev/null
    workingDir: /home/senuser
    env:
    # Use the AIU device
    - name: FLEX_COMPUTE
      value: "SENTIENT"
    - name: FLEX_DEVICE
      value: "PF"
    # Force runtime to use the same heap data structure for everything
    - name: FLEX_OVERWRITE_NMB_FRAME
      value: "1"
    # Needed for multi-AIU runs
    - name: FLEX_UNLINK_DEVMEM
      value: "false"
    # Turn off Python line buffering
    - name: PYTHONUNBUFFERED
      value: "1"
    # HOME might not be set, so set it
    - name: HOME
      value: /home/senuser
    - name: HF_HOME
      value: /home/senuser/models/huggingface_cache
    - name:  HF_HUB_CACHE
      value: /home/senuser/models/huggingface_cache/hub
    - name: HF_DATASETS_CACHE
      value: $HF_HOME/datasets
    # Make the AIU stack quiet
    - name: DTLOG_LEVEL
      value: "error"
    - name: TORCH_SENDNN_LOG
      value: "CRITICAL"
    - name: DT_DEEPRT_VERBOSE
      value: "-1"
    - name: POD_IMAGE
      value: *pod_image
    - name: DEEPVIEW_THRESHOLDS_FOLDERPATH
      value: /home/senuser/models/deepview/layerwise-thresholds
    volumeMounts:
    # Expanded Shared Memory
    - name: dev-shm
      mountPath: /dev/shm
    # Model mount
    - name: shared-models
      mountPath: /home/senuser/models
  volumes:
  - name: dev-shm
    emptyDir:
      medium: Memory
      sizeLimit: 64Gi
  - name: shared-models
    persistentVolumeClaim:
      claimName: shared-models
