# Standard
from contextlib import redirect_stderr, redirect_stdout
import json
import os
import re
import sys

# Third Party
from torch_sendnn import torch_sendnn
import torch

# Local
from deepview.core.generate_minimal_repro import generate_repro_code_unsupported_ops
from deepview.core.layer_debugging import (
    process_output_layer_debugging,
    run_individual_layers,
)
from deepview.utils.model_handler import ModelHandler
from deepview.utils.tee import Tee


def set_environment():
    """Sets environment variables for consistent logging and output behavior during model execution.

    Also removes any pre-existing model output file (`model_output.txt`) to ensure a clean run.
    """
    old_output_file = "model_output.txt"
    if os.path.exists(old_output_file):
        print("Deleting the old model_output.txt..............")
        os.remove(old_output_file)
    os.environ["DTLOG_LEVEL"] = "error"
    os.environ["TORCH_SENDNN_LOG"] = "CRITICAL"
    os.environ["DT_DEEPRT_VERBOSE"] = "-1"
    os.environ["PYTHONUNBUFFERED"] = "1"
    os.environ["COMPILATION_MODE"] = "offline_decoder"


def process_output_unsupported_ops(tool_output_file, logfile, generate_repro_code_flag):
    """Parses the model execution log to extract and report unsupported operations.

    It identifies lines starting with 'DEEPVIEW' that indicate unsupported operations,
    filters unique op names, and writes them to `tool_output_file`. Optionally triggers
    reproduction code generation if unsupported ops are found.

    Args:
        tool_output_file (str): Output file to store processed DEEPVIEW lines and unsupported op summary.
        logfile (str): Path to the complete model output log.
        generate_repro_code_flag (bool): Whether to generate reproduction code for the unsupported ops.
    """
    # All DEEPVIEW output lines are extracted and saved in tool_output_file.
    unknown_nodes = []
    with open(logfile, "r") as infile, open(tool_output_file, "w") as outfile:
        for line in infile:
            if line.startswith("DEEPVIEW"):
                outfile.write(line)
                match = re.search(r"DEEPVIEW Caught error for (.*?):", line)
                if match:
                    node = match.group(1)
                    unknown_nodes.append(node)

        def strip(s):
            return re.sub(r"\x1b\[[0-9;]*m", "", s)

        seen = set()
        unique_unknown_nodes = [
            op
            for op in unknown_nodes
            if not re.match(r".*_\d+$", strip(op))
            and (strip(op) not in seen and not seen.add(strip(op)))
        ]
        if len(unique_unknown_nodes) == 0:
            no_unsup_op = (
                "DEEPVIEW========================================================================\n"
                "DEEPVIEW \033[1mNo unsupported operations detected.\033[0m\n"
            )
            print(no_unsup_op)
            outfile.write(no_unsup_op)
        else:
            unknown_nodes_str = "\n".join(sorted(unique_unknown_nodes))
            final_line = (
                "DEEPVIEW========================================================================\n"
                "DEEPVIEW Unsupported operations list:\n"
                f"{unknown_nodes_str}"
            )
            print(final_line)
            outfile.write(final_line + "\n")

    # Generate reproduction code for unsupported ops (if any)
    if generate_repro_code_flag:
        if len(unique_unknown_nodes):
            print("Generating reproduction code")
            generate_repro_code_unsupported_ops()
        else:
            print("No reproduction code generated as no unsupported operations found.")


def run_model(
    model_type,
    model_path,
    tool_output_file,
    deepview_mode,
    generate_repro_code_flag,
    logfile="model_output.txt",
):
    """Main entry point to run a model and process its execution logs.

    Loads and compiles the model using `ModelHandler`, runs inference,
    and processes the output logs based on the active deepview mode.

    For `layer_debugging` mode, it inserts hooks and runs individual layers.
    For `unsupported_op` mode, it detects unsupported ops in the model.

    Args:
        model_type (str): Type of the model - hf or fms.
        model_path (str): Path to the model checkpoint.
        tool_output_file (str): Path to store filtered and analyzed output (e.g., unsupported ops or failed layers).
        deepview_mode (str): Mode to run DeepView in; can include 'layer_debugging' or 'unsupported_op'.
        generate_repro_code_flag (bool): Whether to generate reproducible test scripts for failure points.
        logfile (str, optional): File to store full execution logs. Defaults to 'model_output.txt'.
    """
    # Prints generated by compile_and_infer are shown in terminal as well as saved in logfile.
    with open(logfile, "a") as f:
        tee = Tee(sys.stdout, f)
        with redirect_stdout(tee), redirect_stderr(tee):
            if generate_repro_code_flag:
                torch_sendnn.preserve_lazyhandle()

            torch.set_default_dtype(torch.float16)
            model_handler = ModelHandler(
                model_type=model_type,
                model_path=model_path,
                prompt="What is the capital of India?",
            )
            model_handler.load_and_compile_model()
            model_handler.prep_input()

            print("Reached first infer call post compile.....")
            try:
                if "layer_debugging" in deepview_mode:
                    model_handler.insert_forward_hooks()
                    if model_type == "hf":
                        print("Support of layer debugging for HF models is WIP")
                        sys.exit()

                model_handler.infer()

                if "layer_debugging" in deepview_mode:
                    model_handler.remove_forward_hooks()
                    with open("model_list.txt", "w") as file:
                        json.dump(
                            {k: list(v) for k, v in model_handler.layer_list.items()},
                            file,
                        )

                    failed_layer, input_shape, datatype = run_individual_layers(
                        logfile, model_path, model_type, model_handler.layer_list
                    )

            except Exception as e:
                print(f"Exception occurred: {e}")

    # Process the logfile to create the tool_output_file
    if "unsupported_op" in deepview_mode:
        process_output_unsupported_ops(
            tool_output_file, logfile, generate_repro_code_flag
        )
    if "layer_debugging" in deepview_mode:
        process_output_layer_debugging(
            tool_output_file,
            logfile,
            generate_repro_code_flag,
            model_path,
            failed_layer,
            input_shape,
            datatype,
        )

    # Since both our modes produce outputs before this line, commenting out the code after that -- this can be enabled in future
    # Update lazyhandle after first run of inference
    # print("Updating lazyhandle")
    # torch_sendnn.update_lazyhandle()
